# Generated by Django 5.0.3 on 2024-05-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient_alter_doctor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.TextField()),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_username', models.TextField()),
                ('doc_password', models.CharField(max_length=50)),
            ],
        ),
    ]
