# Generated by Django 5.0.3 on 2024-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_admin_cred_doctor_cred'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_admin_cred',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('disease', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='admin_cred',
        ),
        migrations.DeleteModel(
            name='doctor_cred',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='languages',
        ),
    ]
