# Generated by Django 5.0.3 on 2024-05-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admincred_appointment_delete_admin_cred_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
    ]
